#!/bin/bash

BINDIR=bin
BINARY=${BINDIR}/charlie
BUILDDIR=build
BUILDINFO=.build.info

if [ $# -ne 1 ]; then
    echo "Usage: ./faire <command>"
    exit 1
fi

function build() {
    if [ ! -d build ]; then
        cmake -H. -B${BUILDDIR}
    fi
    cmake --build ${BUILDDIR}
    echo "LAST_MODIFIED=$(stat -c %Y ${BINARY})" > $BUILDINFO
}

function run() {
    ./${BINARY} $@
}

CMD=$1
case $CMD in
    "build" | "b" )
        build
        ;;
    "run" | "r" )
        MODIFIED=false
        if [ -f ${BUILDINFO} ]; then
            . $BUILDINFO
            MODIFIED_TIME=`stat -c %Y ${BINARY}`
            DIFF=$((${MODIFIED_TIME}-${LAST_MODIFIED}))
            if [ ${DIFF} -gt 0 ]; then
                MODIFIED=true
            fi
        fi
        if [ ! -d ${BINDIR} ] || [ ! -f ${BINARY} ] || [ "${MODIFIED}" = true ]; then
            echo "Building..."
            build
        fi
        run $@
        ;;
    "clean" | "c" )
        echo "Cleaning repository..."
        rm -rf ${BINDIR} ${BUILDDIR} ${BUILDINFO}
        ;;
esac
